USB_VID = 0x239A
USB_PID = 0x8030
USB_PRODUCT = "Tiny Book Variant B"
USB_MANUFACTURER = "Oddly Specific Objects"

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 2
EXTERNAL_FLASH_DEVICES = GD25Q32C
LONGINT_IMPL = MPZ

# No I2S on SAMD51G
CIRCUITPY_AUDIOBUSIO = 0
