// I copied and pasted this (very brief) 
// excerpt from Oprah's book club website.
// Please don't hurt me, I bought the book 
// at Spoonbill & Sugartown in Brooklyn and 
// loved it so much I had to include it in 
// a selection of great literature for
// this demo.

const char * book001 [] = {
"When he woke in the woods in the dark",
"and the cold of the night he'd reach",
"out to touch the child sleeping",
"beside him. Nights dark beyond",
"darkness and the days more gray each",
"one than what had gone before. Like",
"the onset of some cold glaucoma",
"dimming away the world. His hand rose",
"and fell softly with each precious",
"breath. He pushed away the plastic",
"tarpaulin and raised himself in the",
"stinking robes and blankets and",
"looked toward the east for any light",
"but there was none. In the dream from",
"which he'd wakened he had wandered in",
"a cave where the child led him by the",
"hand. Their light playing over the",
"wet flowstone walls. Like pilgrims in",
"a fable swallowed up and lost among",
"the inward parts of some granitic",
"beast. Deep stone flues where the",
"water dripped and sang. Tolling in",
"the silence the minutes of the earth",
"and the hours and the days of it and",
"the years without cease. Until they",
"stood in a great stone room where lay",
"a black and ancient lake. And on the",
"far shore a creature that raised its",
"dripping mouth from the rimstone pool",
"and stared into the light with eyes",
"dead white and sightless as the eggs",
"of spiders. It swung its head low",
"over the water as if to take the",
"scent of what it could not see.",
"Crouching there pale and naked and",
"translucent, its alabaster bones cast",
"up in shadow on the rocks behind it.",
"Its bowels, its beating heart. The",
"brain that pulsed in a dull glass",
"bell. It swung its head from side to",
"side and then gave out a low moan and",
"turned and lurched away and loped",
"soundlessly into the dark.",
"",
"With the first gray light he rose and",
"left the boy sleeping and walked out",
"to the road and squatted and studied",
"the country to the south. Barren,",
"silent, godless. He thought the month",
"was October but he wasnt sure. He",
"hadnt kept a calendar for years. They",
"were moving south. There'd be no",
"surviving another winter here.",
"",
"When it was light enough to use the",
"binoculars he glassed the valley",
"below. Everything paling away into",
"the murk. The soft ash blowing in",
"loose swirls over the blacktop. He",
"studied what he could see. The",
"segments of road down there among the",
"dead trees. Looking for anything of",
"color. Any movement. Any trace of",
"standing smoke. He lowered the",
"glasses and pulled down the cotton",
"mask from his face and wiped his nose",
"on the back of his wrist and then",
"glassed the country again. Then he",
"just sat there holding the binoculars",
"and watching the ashen daylight",
"congeal over the land. He knew only",
"that the child was his warrant. He",
"said: If he is not the word of God",
"God never spoke.",
"",
"When he got back the boy was still",
"asleep. He pulled the blue plastic",
"tarp off of him and folded it and",
"carried it out to the grocery cart",
"and packed it and came back with",
"their plates and some cornmeal cakes",
"in a plastic bag and a plastic bottle",
"of syrup. He spread the small tarp",
"they used for a table on the ground",
"and laid everything out and he took",
"the pistol from his belt and laid it",
"on the cloth and then he just sat",
"watching the boy sleep. He'd pulled",
"away his mask in the night and it was",
"buried somewhere in the blankets. He",
"watched the boy and he looked out",
"through the trees toward the road.",
"This was not a safe place. They could",
"be seen from the road now it was day.",
"The boy turned in the blankets. Then",
"he opened his eyes. Hi, Papa, he",
"said.",
"",
"I'm right here.",
"",
"I know.",
"",
"An hour later they were on the road.",
"He pushed the cart and both he and",
"the boy carried knapsacks. In the",
"knapsacks were essential things. In",
"case they had to abandon the cart and",
"make a run for it. Clamped to the",
"handle of the cart was a chrome",
"motorcycle mirror that he used to",
"watch the road behind them. He",
"shifted the pack higher on his",
"shoulders and looked out over the",
"wasted country. The road was empty.",
"Below in the little valley the still",
"gray serpentine of a river.",
"Motionless and precise. Along the",
"shore a burden of dead reeds. Are you",
"okay? he said. The boy nodded. Then",
"they set out along the blacktop in",
"the gunmetal light, shuffling through",
"the ash, each the other's world",
"entire.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""};
