const char * book006 [] = {
"                  I",
"",
"    Stai per cominciare a leggere il",
"nuovo romanzo Se una notte d'inverno",
"un viaggiatore di Italo Calvino.",
"Rilassati. Raccogliti, Allontana da",
"te ogni altro pensiero. Lascia che il",
"mondo che ti circonda sfumi",
"nell'indistinto. La porta è meglio",
"chiuderla; di là c'è sempre la",
"televisione accesa. Dillo subito,",
"agli altri: «No, non voglio vedere la",
"televisione!» Alza la voce, se no non",
"ti sentono: «Sto leggendo! Non voglio",
"essere disturbato!» Forse non ti",
"hanno sentito, con tutto quel",
"chiasso; dillo più forte, grida:",
"«Sto cominciando a leggere il nuovo",
"romanzo di Italo Calvino! » O se non",
"vuoi non dirlo; speriamo che ti",
"lascino in pace.",
"    Prendi la posizione più comoda:",
"seduto, sdraiato, raggomitolato,",
"coricato. Coricato sulla schiena, su",
"un fianco, sulla pancia. In poltrona,",
"sul divano, sulla sedia a dondolo,",
"sulla sedia a sdraio, sul pouf.",
"Sull'amaca, se hai un'amaca. Sul",
"letto, naturalmente, o dentro il",
"letto. Puoi anche metterti a testa in",
"giù, in posizione yoga, Col libro",
"capovolto, si capisce.",
"    Certo, la posizione ideale per",
"leggere non si riesce a trovarla. Una",
"volta si leggeva in piedi, di fronte",
"a un leggio. Si era abituati a stare",
"fermi in piedi. Ci si riposava così",
"quando si era stanchi d'andare a",
"cavallo. A cavallo nessuno ha mai",
"pensato di leggere; eppure ora l'idea",
"di leggere stando in arcioni, il",
"libro posato sulla criniera del",
"cavallo, magari appeso alle orecchie",
"del cavallo con un finimento",
"speciale, ti sembra attraente. Coi",
"piedi nelle staffe si dovrebbe stare",
"molto comodi per leggere; tenere i",
"piedi sollevati è la prima",
"condizione per godere della lettura.",
"    Bene, cosa aspetti? Distendi le",
"gambe, allunga pure i piedi su un",
"cuscino, su due cuscini, sui",
"braccioli del divano, sugli",
"orecchioni della poltrona, sul",
"tavolino da tè, sulla scrivania, sul",
"pianoforte, sul mappamondo. Togliti",
"le scarpe, prima. Se vuoi tenere i",
"piedi sollevati; se no, rimettitele.",
"Adesso non restare lì con le scarpe",
"in una mano e il libro nell'altra.",
"    Regola la luce in modo che non ti",
"stanchi la vista. Fallo adesso,",
"perché appena sarai sprofondato",
"nella lettura non ci sarà più verso",
"di smuoverti. Fa' in modo che la",
"pagina non resti in ombra, un",
"addensarsi di lettere nere su sfondo",
"grigio, uniformi come un branco di",
"topi; ma sta' attento che non le",
"batta addosso una luce troppo forte e",
"non si rifletta sul bianco crudele",
"della carta rosicchiando le ombre dei",
"caratteri come in un mezzogiorno del",
"Sud. Cerca di prevedere ora tutto",
"ciò che può evitarti d'interrompere",
"la lettura. Le sigarette a portata di",
"mano, se fumi, il portacenere. Che",
"c'è ancora? Devi far pipì? Bene,",
"saprai tu.",
"    Non che t'aspetti qualcosa di",
"particolare da questo libro in",
"particolare. Sei uno che per",
"principio non s'aspetta più niente",
"da niente. Ci sono tanti, più",
"giovani di te o meno giovani, che",
"vivono in attesa d'esperienze",
"straordinarie; dai libri, dalle",
"persone, dai viaggi, dagli",
"avvenimenti, da quello che il domani",
"tiene in serbo. Tu no. Tu sai che il",
"meglio che ci si può aspettare è di",
"evitare il peggio. Questa è la",
"conclusione a cui sei arrivato, nella",
"vita personale come nelle questioni",
"generali e addirittura mondiali. E",
"coi libri? Ecco, proprio perché lo",
"hai escluso in ogni altro campo,",
"credi che sia giusto concederti",
"ancora questo piacere giovanile",
"dell'aspettativa in un settore ben",
"circoscritto come quello dei libri,",
"dove può andarti male o andarti",
"bene, ma il rischio della delusione",
"non è grave.",
"    Dunque, hai visto su un giornale",
"che è uscito Se una notte d'inverno",
"un viaggiatore, nuovo libro di Italo",
"Calvino, che non ne pubblicava da",
"vari anni.",
"    Sei passato in librerìa e hai",
"comprato il volume. Hai fatto bene.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""};
